<a href="https://colab.research.google.com/github/revan-desai/NumPy_basics/blob/main/numpy_linspace_minMaxSum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## linspace

### np.linspace(start , end , number of sample data)

### The linspace() function returns the evenly spaced values over the given interval. The following example returns the 10 evenly separated values over the given interval 5-15

In [2]:
import numpy as np

arr=np.linspace(1,15,10)    # this will give equally space

arr

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [10]:
import numpy as np

b=np.linspace(1,10,10)

print(b)

print(type(b[1]))   #linspace return values in float datatype



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.float64'>


## max()

## min()

## sum()

In [18]:
import numpy as np

b=np.array([[77,55,4],[65,200,80]])

print(np.max(b))

print(np.min(b))

print('addition of all elements in b is ', np.sum(b))

200
4
addition of all elements in b is  481


In [30]:
import numpy as np

b=np.array([[77,55,4],[65,200,80]])

print(b)

print("************************")

print(np.max(b,axis=0))

print(np.max(b,axis=1))

[[ 77  55   4]
 [ 65 200  80]]
************************
[ 77 200  80]
[ 77 200]


In [38]:
import numpy as np

b=np.array([5,10,15,25])

b1=np.array([1,2,3,4])

print(np.sqrt(b))

print("*****************")

print(np.std(b))

print("*****************")

print(np.std(b1))

[2.23606798 3.16227766 3.87298335 5.        ]
*****************
7.39509972887452
*****************
1.118033988749895
