<a href="https://colab.research.google.com/github/revan-desai/NumPy_basics/blob/main/numpy_size_shape_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  size() and shape() of array

In [ ]:
import numpy as np

arr=np.array([[1,5,8],[7,6,9]])

print(np.ndim(arr))

print(np.size(arr))      # will return total elements in an array

print(np.shape(arr))



2
6
(2, 3)


array([[1, 5],
       [8, 7],
       [6, 9]])

# reshape ()--
###np.reshape(arr)--> will produce new array
###and
###arr.reshape --> will make changes into original array

In [8]:
import numpy as np

arr=np.array([[1,5,8],[7,6,9]])

np.reshape(arr,(3,2))   # the reshaped array must contain same number of elements hence be careful while passing values...here 3*2=6
                        # and total elements in original array are also 6


array([[1, 5],
       [8, 7],
       [6, 9]])

In [10]:
import numpy as np

arr=np.array([[1,5,8],[7,6,9],[5,6,11]])

np.ndim(arr)

2

# resize()--

###np.resize(arr)--> will produce new array
###and
###arr.resize --> will make changes into original array



In [ ]:
import numpy as np

arr=np.array([[1,5,8],[7,6,9]])

np.resize(arr,(5,5))     # in resize you can pass any dimensions.....the values will keep on repeating

array([[1, 5, 8, 7, 6],
       [9, 1, 5, 8, 7],
       [6, 9, 1, 5, 8],
       [7, 6, 9, 1, 5],
       [8, 7, 6, 9, 1]])

In [12]:
import numpy as np

arr=np.array([[1,5,8],[7,6,9]])

np.resize(arr,(4,4))

array([[1, 5, 8, 7],
       [6, 9, 1, 5],
       [8, 7, 6, 9],
       [1, 5, 8, 7]])