<a href="https://colab.research.google.com/github/revan-desai/NumPy_basics/blob/main/numpy_matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

arr1=np.array([[12,13,55],[5,9,74]],ndmin=3)   # we have changed the dimensions of array from 2D to 3D

print(arr1.ndim)           # ndmin and ndim are different

print(arr1)

3
[[[12 13 55]
  [ 5  9 74]]]


In [26]:
import numpy as np

arr1=np.array([[12,13,55],[5,9,74]],ndmin=3)

np.shape(arr1)

(1, 2, 3)

## for matrix multiplication condition is:

row of 1st matrix must match column of 2nd matrix or vice versa



In [40]:
import numpy as np

arr1=np.array([[12,88,66]],ndmin=2)

arr2=np.array([[11,98,45],[25,50,60],[56,26,13]],ndmin=3)

print(arr1)
                              # remember it is not necessary to have both matrix should be of equal dimensions
print(arr2)                     # try changing dimensions using ndmin still multiplication will happen only condition is this.....
                                #row of 1st matrix must match column of 2nd matrix or vice versa

result=np.matmul(arr1,arr2)

result

[[12 88 66]]
[[[11 98 45]
  [25 50 60]
  [56 26 13]]]


array([[[6028, 7292, 6678]]])

#dot() is recommended over matmul ....which is same as matmul

In [44]:
import numpy as np

arr1=np.array([[12,88,66]],ndmin=2)

arr2=np.array([[11,98,45],[25,50,60],[56,26,13]],ndmin=2)

result1=np.dot(arr1,arr2)

result1



array([[6028, 7292, 6678]])

In [50]:
import numpy as np
arr1=np.array([12,88,66])

arr2=np.array([[11,98,45],[25,50,60],[56,26,13]])

result3=np.dot(arr1,arr2)

result3

array([6028, 7292, 6678])

## numpy append()


In [51]:
import numpy as np

a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])

c=np.append(a,b,axis=0)   # axis=0 means changes will happen at row level

c

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [54]:
import numpy as np
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])

c1=np.append(a,b,axis=1)   # axis=1 means changes will happen at column level
c1

array([[10, 20, 30, 11, 21, 31],
       [40, 50, 60, 42, 52, 62],
       [70, 80, 90, 73, 83, 93]])

## numpy sum()

In [61]:
a=np.array([[10, 20, 30], [40, 50, 60]])
b=np.array([[11, 21, 31], [42, 52, 62]])

sum1=np.sum(a)

sum2=np.sum(b)

print(sum1)

print(sum2)

210
219


### but what if you want to add two array.....then use add() function

In [65]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])
print(a)
print('*****************************')
print(b)
print('*****************************')
sum3=np.add(a,b)

print(sum3)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
*****************************
[[11 21 31]
 [42 52 62]
 [73 83 93]]
*****************************
[[ 21  41  61]
 [ 82 102 122]
 [143 163 183]]


## transpose ()

In [73]:
import numpy as np

a=np.array([[55,66,77]])   # this array has to be in 2 dimensional to transpose try in 1- dimension dont work

print(a)

print(np.shape(a))

b=np.transpose(a)

print(b)

print(np.shape(b))

[[55 66 77]]
(1, 3)
[[55]
 [66]
 [77]]
(3, 1)


## unique()

In [80]:
import numpy as np

a = np.array([[4, 1, 0, 5, 5], [4, 1, 0, 5, 5], [2, 3, 4, 3, 3],[5, 9, 8, 9, 9],[2, 3, 4, 10, 10]])

print(a)

print('******************************')
u=np.unique(a,axis=1)   # axis=1 means only unique column will show.....

print(u)               # remember unique function removes duplicate column and also arrange column in ascending manner with respect to first row.

[[ 4  1  0  5  5]
 [ 4  1  0  5  5]
 [ 2  3  4  3  3]
 [ 5  9  8  9  9]
 [ 2  3  4 10 10]]
[[ 0  1  4  5]
 [ 0  1  4  5]
 [ 4  3  2  3]
 [ 8  9  5  9]
 [ 4  3  2 10]]


In [86]:
import numpy as np

a = np.array([[4, 1, 0, 5, 5], [4, 1, 0, 5, 5], [2, 3, 4, 3, 3],[5, 9, 8, 9, 9],[2, 3, 4, 10, 10]])

print(a)

print('******************************')
u1=np.unique(a,axis=1)   # axis=1 means only unique rows will show and in ascending manner with respect to first column

print(u1)


[[ 4  1  0  5  5]
 [ 4  1  0  5  5]
 [ 2  3  4  3  3]
 [ 5  9  8  9  9]
 [ 2  3  4 10 10]]
******************************
[[ 0  1  4  5]
 [ 0  1  4  5]
 [ 4  3  2  3]
 [ 8  9  5  9]
 [ 4  3  2 10]]
