<a href="https://colab.research.google.com/github/revan-desai/NumPy_basics/blob/main/numpy_creating_array_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0-D zero dimensional array

In [ ]:
import numpy as np

a=np.array(12)   # dont put [] here ,it will make this array one dimensional not zero.

print(a)
print(a.ndim)


12
0


## 1-D one dimensional array

In [ ]:
import numpy as np
a1=np.array([5,9,6,7,3])
print(a1)
print(a1.ndim)

## 2-D one dimensional array

In [2]:
import numpy as np
a2=np.array([[99,44,33],[25,47,12]])
print(a2)
print("dimention of this array are", a2.ndim)


[[99 44 33]
 [25 47 12]]
dimention of this array are 2


## 3-D one dimensional array

In [10]:
import numpy as np
a3=np.array([[[55,23,11],[25,98,74]],[[25,63,48],[11,79,43]]])
print(a3)
print(a3.ndim)

[[[55 23 11]
  [25 98 74]]

 [[25 63 48]
  [11 79 43]]]
3


In [13]:
arr=np.array(5)         # zero dimensional array

arr1=np.array([1,3,8])  # 1 dimensional array

arr2=np.array([[41,12,59],[58,23,45]])        # 2 dimensional array
# print(arr2[1])

arr3=np.array([ [ [1,2,3],[8,9,1] ],[ [2,3,5],[8,7,3] ] ])

print("dimensions of arr are" , arr.ndim )

print("dimensions of arr1 are" , arr1.ndim )

print("dimensions of arr2 are" , arr2.ndim )

print("dimensions of arr3 are" , arr3.ndim )

dimensions of arr are 0
dimensions of arr1 are 1
dimensions of arr2 are 2
dimensions of arr3 are 3
