<a href="https://colab.research.google.com/github/revan-desai/NumPy_basics/blob/main/numpy_log()%26random().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

arr=np.array([1,5,8,16])

l1=np.log(arr)

l2=np.log2(arr)

l3=np.log10(arr)

print(l1)

print(l2)

print(l3)

[0.         1.60943791 2.07944154 2.77258872]
[0.         2.32192809 3.         4.        ]
[0.         0.69897    0.90308999 1.20411998]


# random()--- all functions covered here

## 1. np.random.random(())

In [2]:
import numpy as np

a=np.random.random((3,3))

print(a)

[[0.94026551 0.02539262 0.58772664]
 [0.85006259 0.42922649 0.92412568]
 [0.57488298 0.88231317 0.06466053]]


In [5]:
import numpy as np

a1=np.random.random((2,3,3))

print(a1)

[[[0.74121996 0.99216078 0.95355413]
  [0.06083892 0.84454787 0.34541165]
  [0.41005451 0.33501009 0.55077185]]

 [[0.87672368 0.96017803 0.61764365]
  [0.02328607 0.43037559 0.12590854]
  [0.79602134 0.25940668 0.74378101]]]


##2. random.rand() -->only difference between random.random()and random.rand() is syntax as i have tested

In [7]:
import numpy as np

a1=np.random.rand(3,3)
print(a1)

[[[0.3561597  0.40894748 0.3574062 ]
  [0.90984895 0.67277796 0.49029981]
  [0.87443136 0.85720667 0.04367079]]

 [[0.55437095 0.41366466 0.1022854 ]
  [0.85415337 0.9254193  0.66078089]
  [0.61503139 0.13226524 0.17104639]]]


In [8]:
import numpy as np

a2=np.random.rand(2,3,3)

print(a2)

[[[0.45377075 0.92172489 0.9297905 ]
  [0.32421727 0.11627038 0.13381086]
  [0.40698748 0.3007575  0.55852294]]

 [[0.85618927 0.89058462 0.43459661]
  [0.4089093  0.17792398 0.32373227]
  [0.31981718 0.72865331 0.16037733]]]


## 3.random.randn()---> extra n in randn stands  for negative so it provide both positive and negative values

only difference in random.rand() and random.randn()  is latter provide negative values as well along with positive values

In [9]:
import numpy as np

b2=np.random.randn(3,3)

print(b2)

[[ 0.30107259 -0.84561928 -0.73938142]
 [ 0.16254013  1.25713167 -1.09628041]
 [ 0.6736893  -0.33614297  1.00727664]]


##4.random.randint()

In [34]:
import numpy as np

i=np.random.randint(1,5)  # will return any random number between 1 to 4 ......5 not included

print(i)

4


In [36]:
import numpy as np

i=np.random.randint(1,5,size=(3,3))      # will return random matrix

print(i)

[[1 2 1]
 [2 4 4]
 [3 2 4]]


## random.choice()-->here you can pass percentage for each value to generate

In [37]:
import numpy as np

names=['rohan','john','bob','sunny']

ch=np.random.choice(names,size=(3,3),p=[0.5,0.5,0,0]) #here  we gave 50% chance to rohan and john .....and 0% for bob and sunny

print(ch)

[['rohan' 'rohan' 'rohan']
 ['rohan' 'rohan' 'john']
 ['john' 'rohan' 'john']]


In [38]:
import numpy as np

names=['rohan','john','bob','sunny']

ch=np.random.choice(names,size=(3,3),p=[0.5,0.2,0.3,0])

print(ch)

[['rohan' 'bob' 'rohan']
 ['rohan' 'bob' 'bob']
 ['rohan' 'john' 'bob']]
